In [1]:
import pandas as pd 
import numpy as np 

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

## Dimensions of Array

In [3]:
arr0 = np.array(9) ##scalor or 0-D array
arr1= np.array([1,2,3,4,5]) ##1-D array
arr2= np.array([[1,2,3],[4,5,6]]) ##2-D array
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) ##3-D array

print("Its scalar or 0-D array: ", arr0)
print("Its 1-D array: ", arr1)
print("Its 2-D array: ", arr2)
print("Its 3-D array: ", arr3)

print(arr.ndim)
print(arr1.ndim)      ##ndim tells how many dimensions that array has
print(arr2.ndim)
print(arr3.ndim)

Its scalar or 0-D array:  9
Its 1-D array:  [1 2 3 4 5]
Its 2-D array:  [[1 2 3]
 [4 5 6]]
Its 3-D array:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
1
2
3


In [4]:
arr= np.array([1,2,3], ndmin=5) ##ndmin to define no of dimensions
print(arr)
print(arr.ndim)

[[[[[1 2 3]]]]]
5


In [5]:
arr = np.array([1,2,3,4,5])
print(arr[0])        ##accessing 1-d arrays
print(arr[2]+arr[3])

1
7


In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("2nd element on first row: ",arr[0,1]) ##accessing 2-d arrays where 0 is dimension, 1 is column

[[1 2 3]
 [4 5 6]]
2nd element on first row:  2


**Accessing 2-D arrays**

In [7]:
arr = np.array([['a','b','c'],['d','e','f']])
print(arr)
print(arr[1,1]) ##1 means second row as row starts from 0, and 1 means 2nd value as value also starts from 0 index

[['a' 'b' 'c']
 ['d' 'e' 'f']]
e


**Accessing 3-D arrays**

In [8]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print("3rd element on second row of 1st dimension: ",arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3rd element on second row of 1st dimension:  6


**Negative Indexing**

In [9]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


## Array Slicing

In [10]:
arr = np.array([1,2,3,4,5,6])
print(arr[2:5]) ##includes the start index, but excludes the end index.
print(arr[4:]) ##includes elements from index 4 to end
print(arr[:4]) ##includes elements till index 4 which is not included
print(arr[-3:-1]) ##negative slicing -reverse array from index -1 means last item to -3 item, -1 item isn't included

[3 4 5]
[5 6]
[1 2 3 4]
[4 5]


## Step

In [11]:
arr = np.array([1,2,3,4,5,6,7])
arr2= np.array(['apple','banana','orange'])
print(arr[1:5:2]) #[start:stop:step] 2 in last means print every second element
print(arr[1:5:1]) #prints every 1st element
print(arr[::1]) #prints whole array
print(arr.dtype) #prints data type of array
print(arr2.dtype)

[2 4]
[2 3 4 5]
[1 2 3 4 5 6 7]
int64
<U6


In [12]:
arr = np.array([[1,2,3,4,5],[5,7,8,9,10]])
print(arr[1,1:4]) #1->second array, 1:4-> elements from 1 index to 4 which is not included
print("\n",arr[0:2,1:4]) #returns a 2-d array, for both, 1:4 is working, 0:2 is for directing arrays

[7 8 9]

 [[2 3 4]
 [7 8 9]]


## Data types

In [13]:
arr = np.array([1,2,3,4,5,6,7])
arr1= np.array([1,2,3,4,5,6,7], dtype='S') ## we defined expected output as string here
arr2= np.array(['apple','banana','orange'])
arr3= np.array([1,2,3,4,5,6,7], dtype='i4')

print(arr)
print(arr1)
print(arr3)
print(arr.dtype) #prints data type of array
print(arr2.dtype)

[1 2 3 4 5 6 7]
[b'1' b'2' b'3' b'4' b'5' b'6' b'7']
[1 2 3 4 5 6 7]
int64
<U6


## Changing data type

In [14]:
arr = np.array([1.2,1.1,2.3])

arr2= arr.astype('i') # we changed datatype float to int
arr3= arr.astype(bool) # we changed datatype float to boolean
print(arr2)
print(arr3)
print(arr2.dtype)
print(arr3.dtype)

[1 1 2]
[ True  True  True]
int32
bool


## Numpy Copy vs View

### Numpy Copy

In [15]:
arr = np.array([1,2,3,4,5])
arr2= arr.copy() 
arr[0]=9 #changes the item of original array

print(arr)
print(arr2) #copy array is new array which is not affected by the changes in original array

[9 2 3 4 5]
[1 2 3 4 5]


### Numpy View

In [16]:
arr = np.array([1,2,3,4,5])
arr2= arr.view()
arr[0]=9 #changes the item of original array

print(arr)
print(arr2) #view is the original array which is affected by the changes in original array



[9 2 3 4 5]
[9 2 3 4 5]


In [17]:
arr = np.array([1,2,3,4,5])

arr2= arr.copy()
arr3= arr.view()

print(arr2.base)
print(arr3.base)

None
[1 2 3 4 5]


## Numpy Shapes
The shape of an array is the number of elements in each dimension.

In [18]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr2= np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr)
print(arr.shape) #has 2 dimensions where each dimension contain 4 elements
print(arr2.shape) #has 3 dimensions where each dimension contain 3 elements

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
(3, 3)


In [19]:
arr = np.array([1,2,3,4], ndmin=5) #put dimension as 5
print(arr.shape) # 1,1,1,1 are extra or dummy dimensions of size 1. 4 is the actual length of dimension

arr2 = np.array([1,2,3], ndmin=3)
print(arr2.shape)

(1, 1, 1, 1, 4)
(1, 1, 3)


## Reshaping array
reshaping means changing the shape of array

In [20]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]) #reshape into 3-d array

arr2 = arr.reshape(2,3,2) #outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements
print(arr2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [21]:
arr = np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(2,4).base) #returns view

[1 2 3 4 5 6 7 8]


In [22]:
arr = np.array([1,2,3,4,5,6,7,8])

arr2 = arr.reshape(2,2,-1)
print(arr2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Flattening the array
converting a multidimensional array into a 1D array.

In [23]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.reshape(-1)) #converts 2d array into 1d

[1 2 3 4 5 6]


## Iterating the array

In [24]:
arr=np.array([1,2,3,4,5]) #iterating 1-d array
for x in arr:
    print(x)

arr1= np.array([[1,2,3],[4,5,6]]) #iterating 2-d array
for y in arr1:
    print(y)

arr2= np.array([[1,2,3],[4,5,6],[7,8,9]]) #iterating 3-d array
for y in arr2:
    print("\n",y)

1
2
3
4
5
[1 2 3]
[4 5 6]

 [1 2 3]

 [4 5 6]

 [7 8 9]


In [25]:
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
   for y in x:       #prints scalar values out of 2-d array
    print(y)

arr1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #iterating 3d array
for a in arr1:
  for b in a:
    for c in b:
        print('\t',c)

1
2
3
4
5
6
	 1
	 2
	 3
	 4
	 5
	 6
	 7
	 8
	 9
	 10
	 11
	 12


## Simplifying Iteration with nditer()
NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [26]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr): #no need of using for loop for higher dimensionality
    print(x)

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')
np.bytes_(b'10')
np.bytes_(b'11')
np.bytes_(b'12')


In [27]:
arr = np.array([1,2,3])
arr1 = np.array([[1,2,3],[4,5,6]]) 
for idx, x in np.ndenumerate(arr): #returns index of array
    print(idx,x)

for ind, y in np.ndenumerate(arr1):
    print(ind,y)

(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


## Joining numpy arrays

In [28]:
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])

arr = np.concatenate((arr1,arr2)) #joins two arrays
print(arr)

[1 2 3 4 5 6]


In [29]:
arr1= np.array([[1,2],[3,4]])
arr2= np.array([[5,6],[7,8]])

arr = np.concatenate((arr1, arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [30]:
arr1= np.array([[1,2],[3,4]])
arr2= np.array([[5,6],[7,8]])

arr = np.stack((arr1,arr2),axis=1) #same as concatenation, the only difference is that stacking is done along a new axis.
print(arr)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [31]:
arr1= np.array([[1,2],[3,4]])
arr2= np.array([[5,6],[7,8]])

arr = np.hstack((arr1,arr2)) #stack along rows
arr3= np.vstack((arr1,arr2)) #stack along columns
print(arr)
print(arr3)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [32]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.dstack((arr1,arr2)) #stack along the height
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## Numpy splitting array

In [33]:
arr = np.array([1,2,3,4,5,6])

newarr= np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [34]:
arr = np.array([1,2,3,4,5,6])

newarr= np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

arr2 = np.array([[1,2],[3,4],[5,6],[7,8]]) #splitting 2d array
newarr2 = np.array_split(arr2,3)
print(newarr2)

arr3= np.array([[1,2,3],[4,5,6],[7,8,9]])
newarr3= np.hsplit(arr3,3) #split the 2-D array into three 2-D arrays along columns
print(newarr3)

[1 2]
[3 4]
[5 6]
[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


## Searching Arrays

In [ ]:
arr = np.array([1,2,3,4,5,4,4])

x= np.where(arr==4)
print(x)                     #means value 4 is present at index 3 5 and 6

(array([3, 5, 6]),)


In [37]:
#find the values which are even
arr = np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)

#find the values which are odd
arr1 = np.array([1,2,3,4,5,6,7,8])
y=np.where(arr1%2==1)
print(y)

(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)


The searchsorted() method is assumed to be used on sorted arrays.

In [41]:
#Find the indexes where the value 7 should be inserted:
arr = np.array([6,8,7,9])
x= np.searchsorted(arr,7)
print(x)
#7 should be inserted on index 1 to remain the sort order

1


In [ ]:
#Find the indexes where the value 7 should be inserted, starting from right
arr = np.array([6,7,8,9])
x= np.searchsorted(arr,7, side='right')
print(x)
#7 should be inserted on index 2 to remain the sort order from right side

2


In [ ]:
arr = np.array([1,3,5,7])
x=np.searchsorted(arr,[2,4,6]) #this would be inserted in original array to maintain the order
print(x)

[1 2 3]


## Sorting Arrays

In [48]:
arr = np.array([3,4,1,0,2,3]) #numerical sort
x=np.sort(arr)
print(x)

arr1= np.array(['banana','cherry','apple']) #alphabetical sort
y=np.sort(arr1)
print(y)

arr2= np.array([True, False, True]) #boolean sort
z=np.sort(arr2)
print(z)

arr3= np.array([[3,2,0],[1,5,4]]) #2d array sort
a=np.sort(arr3)
print(a)

[0 1 2 3 3 4]
['apple' 'banana' 'cherry']
[False  True  True]
[[0 2 3]
 [1 4 5]]


## Numpy Array Filter
Getting some elements out of an existing array and creating a new array out of them is called filtering.
In NumPy, you filter an array using a boolean index list.

In [49]:
#Create an array from the elements on index 0 and 2:
arr = np.array([41,42,43,44])
x= [True, False, True, False] #returns values with True only
newarr= arr[x]
print(newarr)

[41 43]


In [50]:
#Create a filter array that will return only values higher than 42:
arr = np.array([41,42,43,44])

#Create an empty array
filter_arr =[]

#Looping through each element
for x in arr:
    if x>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
#Create a filter array that will return only even elements from the original array:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr =[] #we create this to get the returned array in it
for x in arr:
    if x % 2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(newarr)

[ 2  4  6  8 10]


### Ez pz method (easier than looping)

In [53]:
arr = np.array([41,42,43,44])

filter_arr = arr>42
newarr=arr[filter_arr]
print(newarr)

[43 44]


In [54]:
#Create a filter array that will return only even elements from the original array:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr= arr%2==0
newarr=arr[filter_arr]
print(newarr)

[ 2  4  6  8 10]
